<a href="https://colab.research.google.com/github/pb-roshith/power-plant-energy-output-prediction-ANN/blob/main/Artificial_Neural_Network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [5]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [6]:
tf.__version__

'2.12.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [18]:
dataset = pd.read_excel('Combined-Cycle-Power-Plant.xlsx')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [19]:
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [20]:
x.shape

(9568, 4)

In [21]:
y.shape

(9568,)

### Splitting the dataset into the Training set and Test set

In [23]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [25]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [30]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [40]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [41]:
ann.compile(optimizer='adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [42]:
ann.fit(x_train, y_train, batch_size=32 , epochs=100)

Epoch 1/100
240/240 [==============================] - 2s 3ms/step - loss: 442.8784
Epoch 2/100
240/240 [==============================] - 1s 2ms/step - loss: 26.4236
Epoch 3/100
240/240 [==============================] - 1s 2ms/step - loss: 26.6615
Epoch 4/100
240/240 [==============================] - 1s 2ms/step - loss: 26.9841
Epoch 5/100
240/240 [==============================] - 1s 2ms/step - loss: 26.7994
Epoch 6/100
240/240 [==============================] - 1s 2ms/step - loss: 27.5399
Epoch 7/100
240/240 [==============================] - 1s 2ms/step - loss: 27.9777
Epoch 8/100
240/240 [==============================] - 1s 2ms/step - loss: 28.8488
Epoch 9/100
240/240 [==============================] - 1s 4ms/step - loss: 28.0191
Epoch 10/100
240/240 [==============================] - 1s 4ms/step - loss: 30.9230
Epoch 11/100
240/240 [==============================] - 1s 4ms/step - loss: 29.0534
Epoch 12/100
240/240 [==============================] - 1s 3ms/step - loss: 28.8577


### Predicting the results of the Test set

In [44]:
y_pred = ann.predict(x_test)
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)), 1))

60/60 [==============================] - 0s 1ms/step
[[432.58 431.23]
 [460.58 460.01]
 [465.66 461.14]
 ...
 [472.45 473.26]
 [438.41 438.  ]
 [457.8  463.28]]
